- type: job
  id: SecurityOfficer
  name: job-name-security
  description: job-description-security
  playTimeTracker: JobSecurityOfficer
  subnames:
  - Male: офицер охраны
  - Male: оперативник СБ
  - Male: инструктор СБ
  - Male: патрульный офицер
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 10h # Corvax-RoleTime
    - !type:AgeRequirement
      minAge: 22 # WL-Changes-AgeRequirement
    - !type:TraitsRequirement #Corvax-TraitsRequirement
      inverted: true
      traits:
      - Muted
  startingGear: SecurityOfficerGear
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  - Cryogenics
  - GenpopEnter
  - GenpopLeave
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  # WL-Skills-start
  bonusSkillPoints: 6
  defaultSkills:
    Bureaucracy: 2
    Eva: 3
    Forensics: 2
    Combat: 3
    Weapons: 3
  # WL-Skills-end

- type: startingGear
  id: SecurityOfficerGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    ears: ClothingHeadsetSecurity
    pocket1: WeaponPistolMk58
  storage:
    back:
    - Flash
    - MagazinePistol

- type: chameleonOutfit
  id: SecurityOfficerChameleonOutfit
  job: SecurityOfficer
  hasMindShield: true
  equipment:
    head: ClothingHeadHatBeretSecurity
    mask: ClothingMaskGasSecurity
    neck: Dinkystar
    gloves: ClothingHandsGlovesColorBlack
