- type: job
  id: SeniorEngineer
  name: job-name-senior-engineer
  description: job-description-senior-engineer
  playTimeTracker: JobSeniorEngineer
  requirements:
    - !type:RoleTimeRequirement
      role: JobAtmosphericTechnician
      time: 6h
    - !type:RoleTimeRequirement
      role: JobStationEngineer
      time: 6h
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 60h # 60 hrs
      # WL-Changes-start
    - !type:AgeRequirement
      minAge: 26
      # WL-Changes-end
  weight: 9
  startingGear: SeniorEngineerGear
  icon: "JobIconSeniorEngineer"
  supervisors: job-supervisors-ce
  access:
  - Maintenance
  - Engineering
  - External
  - Atmospherics
  # WL-Skills-start
  bonusSkillPoints: 5
  defaultSkills:
    Bureaucracy: 2
    Eva: 3
    IT: 2
    Atmospherics: 3
    Construction: 3
    Electrical: 3
    Generators: 3
    ComplexDevices: 2
  # WL-Skills-end

- type: startingGear
  id: SeniorEngineerGear
  equipment:
    shoes: ClothingShoesBootsWork
    id: SeniorEngineerPDA
    eyes: ClothingEyesGlassesMeson
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineering

- type: chameleonOutfit
  id: SeniorEngineerChameleonOutfit
  job: SeniorEngineer
  equipment:
    head: ClothingHeadHatBeretEngineering
    mask: ClothingMaskBreath
    neck: ClothingNeckScarfStripedOrange
    outerClothing: ClothingOuterWinterEngi
    gloves: ClothingHandsGlovesColorYellow
    shoes: ClothingShoesBootsMag
