- type: job
  id: Quartermaster
  name: job-name-qm
  description: job-description-qm
  playTimeTracker: JobQuartermaster
  subnames:
  - Male: начальник снабжения
  requirements:
#    - !type:RoleTimeRequirement
#      role: JobCargoTechnician
#      time: 21600 #6 hrs
    - !type:RoleTimeRequirement
      role: JobSalvageSpecialist
      time: 10h # Corvax-RoleTime 2.5
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 10h
    - !type:OverallPlaytimeRequirement
      time: 40h
    - !type:AgeRequirement
      minAge: 24 # WL-Changes-AgeRequirement
    - !type:TraitsRequirement #Corvax-TraitsRequirement
      inverted: true
      traits:
      - Muted
  weight: 10
  startingGear: QuartermasterGear
  icon: "JobIconQuarterMaster"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Cargo
  - Salvage
  - Quartermaster
  - Maintenance
  - External
  - Command
  - Brig
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  # WL-Skills-start
  bonusSkillPoints: 8
  defaultSkills:
    Bureaucracy: 3
    Eva: 3
    Piloting: 2
  # WL-Skills-end

- type: startingGear
  id: QuartermasterGear
  equipment:
    id: QuartermasterPDA
    ears: ClothingHeadsetQM
    belt: BoxFolderClipboardThreePapers
    pocket1: AppraisalTool
  storage:
    back:
    - Flash

- type: chameleonOutfit
  id: QuartermasterChameleonOutfit
  job: Quartermaster
  hasMindShield: true
  equipment:
    head: ClothingHeadHatQMsoft
    eyes: ClothingEyesGlassesSunglasses
    mask: ClothingMaskBreath
    outerClothing: ClothingOuterWinterQM
    neck: ClothingNeckCloakQm
    gloves: ClothingHandsKnuckleDustersQM
