- type: job
  id: Pilot
  name: job-name-pilot
  description: job-description-pilot
  playTimeTracker: JobPilot
  subnames:
  - Male: космический патрульный
  requirements:
  - !type:DepartmentTimeRequirement
    department: Security
    time: 20h
  - !type:AgeRequirement
    minAge: 22 # WL-Changes-AgeRequirement
  - !type:TraitsRequirement
    inverted: true
    traits:
    - Muted
  startingGear: PilotGear
  icon: "JobIconPilot"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  # WL-Skills-start
  bonusSkillPoints: 6
  defaultSkills:
    Bureaucracy: 2
    Eva: 3
    Piloting: 3
    Forensics: 2
    Combat: 3
    Weapons: 3
  # WL-Skills-end

- type: startingGear
  id: PilotGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: PilotPDA
    ears: ClothingHeadsetSecurity
    pocket1: WeaponPistolMk58
  storage:
    back:
    - Flash
    - MagazinePistol

- type: chameleonOutfit
  id: PilotChameleonOutfit
  job: Pilot
  hasMindShield: true
  equipment:
    head: ClothingHeadHatBeretSecurity
    eyes: ClothingEyesGlassesSecurity
    mask: ClothingMaskGasSecurity
    neck: Dinkystar
    gloves: ClothingHandsGlovesColorBlack
