- type: job
  id: Chef
  name: job-name-chef
  description: job-description-chef
  playTimeTracker: JobChef
  subnames:
  - Male: су-шеф
  - Male: мясник
  - Male: кондитер
  - Male: пекарь
  - Male: повар
  - Male: кулинар
  requirements:
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 1h # Corvax-RoleTime
  startingGear: ChefGear
  icon: "JobIconChef"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  - Kitchen
  extendedAccess:
  - Hydroponics
  - Bar
  # WL-Skills-start
  bonusSkillPoints: 17
  defaultSkills:
    Anatomy: 2
    Botany: 2
    Cooking: 3
  # WL-Skills-end

- type: startingGear
  id: ChefGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: ChefPDA
    ears: ClothingHeadsetService
    belt: ClothingBeltChefFilled
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: ChefChameleonOutfit
  job: Chef
  equipment:
    head: ClothingHeadHatChef
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskItalianMoustache
    neck: ClothingNeckScarfStripedBrown
    outerClothing: ClothingOuterJacketChef
    gloves: ClothingHandsGlovesColorWhite
    shoes: ClothingShoesChef
