- type: job
  id: Scientist
  name: job-name-scientist
  description: job-description-scientist
  playTimeTracker: JobScientist
  subnames:
  - Male: робототехник
  - Male: ксеноархеолог
  - Male: аномалист
  - Male: ксенобиолог
  - Male: химик-исследователь
  requirements:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 5h # Corvax-RoleTime
    - !type:AgeRequirement
      minAge: 24 # WL-Changes-AgeRequirement
  startingGear: ScientistGear
  icon: "JobIconScientist"
  supervisors: job-supervisors-rd
  access:
  - Research
  - Maintenance
  # WL-Skills-start
  bonusSkillPoints: 18
  defaultSkills:
    Bureaucracy: 2
    ComplexDevices: 2
    Science: 3
  # WL-Skills-end

- type: startingGear
  id: ScientistGear
  equipment:
    ears: ClothingHeadsetScience
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: ScientistChameleonOutfit
  job: Scientist
  equipment:
    head: ClothingHeadBandSkull
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskGas
    neck: ClothingNeckTieSci
    outerClothing: ClothingOuterCoatRnd
    gloves: ClothingHandsGlovesLatex
