- type: job
  id: IAA
  name: job-name-iaa
  description: job-description-iaa
  playTimeTracker: JobIAA
  requirements:
  - !type:DepartmentTimeRequirement
    department: Command
    time: 20h
  - !type:DepartmentTimeRequirement
    department: Security
    time: 10h
  - !type:AgeRequirement
    minAge: 27 # WL-Changes-AgeRequirement
  - !type:TraitsRequirement
    inverted: true
    traits:
    - Muted
  startingGear: IAAGear
  icon: "JobIconIAA"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
  - Service
  - Brig
  - Maintenance
  - Command
  - External
  - Lawyer
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  # WL-Skills-start
  bonusSkillPoints: 8
  defaultSkills:
    Bureaucracy: 3
    Forensics: 2
  # WL-Skills-end

- type: startingGear
  id: IAAGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: IAAPDA
    eyes: ClothingEyesGlassesSunglasses
    ears: ClothingHeadsetIAA
    pocket2: BookSpaceLaw
  inhand:
    - BriefcaseIAAFilled

- type: chameleonOutfit
  id: IAAChameleonOutfit
  job: IAA
  hasMindShield: true
  equipment:
    head: ClothingHeadHatBowlerHat
    eyes: ClothingEyesGlassesSunglasses
    # Corvax-WL-Tweak-Start
    outerClothing: ClothingOuterCoatDetectiveDark
    neck: ClothingNeckLawyerbadge
    # Corvax-WL-Tweak-End
    gloves: ClothingHandsGlovesColorWhite
    mask: ClothingMaskBreath
