- type: job
  id: SeniorResearcher
  name: job-name-senior-researcher
  description: job-description-senior-researcher
  playTimeTracker: JobSeniorResearcher
  requirements:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 60h
      # WL-Changes-start
    - !type:AgeRequirement
      minAge: 26
      # WL-Changes-end
  weight: 9
  startingGear: SeniorResearcherGear
  icon: "JobIconSeniorResearcher"
  supervisors: job-supervisors-rd
  access:
  - Research
  - Maintenance
  # WL-Skills-start
  bonusSkillPoints: 15
  defaultSkills:
    Bureaucracy: 2
    IT: 2
    Chemistry: 2
    ComplexDevices: 2
    Science: 3
  # WL-Skills-end

- type: startingGear
  id: SeniorResearcherGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: SeniorResearcherPDA
    ears: ClothingHeadsetScience

- type: chameleonOutfit
  id: SeniorResearcherChameleonOutfit
  job: SeniorResearcher
  equipment:
    head: ClothingHeadHatBeretRND
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskGas
    neck: ClothingNeckTieSci
    outerClothing: ClothingOuterCoatLabSeniorResearcher
    gloves: ClothingHandsGlovesLatex
